### ISSUE TITLE
user_id is always blank

### ISSUE THREAD

**Issue by iredmedia** [kyranb/Footprints#18]
I'm noticing that Visits "user_id" is never being set in my system. My registration is unconventional (occurs when another resource is created), and I'm wondering if this might be the cause. 

Are we listening for an event on User ```created``` in this package? 

Any help is greatly appreciated!

**Comment by iredmedia** [comment]
I've done some logging to check what's going on. Seems the USER id is found, but Visit::previousVisits is returning an empty object :\ 

```
public function assignPreviousVisits() {
    \Log::info('assignPreviousVisits');
    \Log::info('Key: ' . $this->getKey());
    \Log::info(json_encode(Visit::previousVisits()));
...

[2017-11-23 16:24:09] local.INFO: bootTrackRegistrationAttribution  
[2017-11-23 16:24:09] local.INFO: assignPreviousVisits  
[2017-11-23 16:24:09] local.INFO: Key: 43  
[2017-11-23 16:24:09] local.INFO: {}  
```

**Comment by kyranb** [comment]
@iredmedia Yes, we are listening for the the `created` event on the model used (User by default): https://github.com/kyranb/Footprints/blob/master/src/TrackRegistrationAttribution.php#L19

**Comment by iredmedia** [comment]
Thanks for the reply! 

In my signup I call User::create, so in theory this should be working :\ Visit::previousVisits() seems to be null (causing no ID to be assigned to a previous record) despite having hit other pages. Is scopePreviousVisits() the same function (magic function, I think)?

Cheers!

**Comment by kyranb** [comment]
Did you end up having any luck with this?

**Comment by iredmedia** [comment]
Sorry for the delay after the delay. I honestly cannot remember, but I'm assuming all is well

**Comment by mzaman** [comment]
Has anyone made progress or found a solution for this blank user_id issue? I'm curious to know if this issue has been addressed or if there are any updates regarding its resolution

**Comment by bilfeldt** [comment]
Have you implemented the `CaptureAttributionDataMiddleware`? Try adding a debug log in there to make sure it's called correctly.

**Comment by mzaman** [comment]
Hi @bilfeldt 
Thanks for your quick response. In the installation example, the middleware was initially added to the global HTTP middleware. However, it consistently generated records with an empty user id in my case. 

The issue was resolved by moving `CaptureAttributionDataMiddleware` to the web middleware group. 
However, the `user_id` is populated only when a user is already logged in. Following a redirection from an external site (where used `disable_on_authentication' => false` and `disable_internal_links => true` in config), records are added for the presence of  utm query parameters in the redirected URL. the connection to the initial visit's tracking is lost. This persists even after subsequent user registration and/or login.
Appreciate your help.

**Comment by bilfeldt** [comment]
> Hi @bilfeldt Thanks for your quick response. In the installation example, the middleware was initially added to the global HTTP middleware. However, it consistently generated records with an empty user id in my case.
> 
> The issue was resolved by moving `CaptureAttributionDataMiddleware` to the web middleware group. However, the `user_id` is populated only when a user is already logged in. Following a redirection from an external site (where used `disable_on_authentication' => false` and `disable_internal_links => true` in config), records are added for the presence of utm query parameters in the redirected URL. the connection to the initial visit's tracking is lost. The `user_id` fails to update even after subsequent user logins; however, it functions correctly for subsequent user registrations. This identifier is crucial for linking various requests performed by the same user. Appreciate your help, @bilfeldt

I am not able to fully imagine the setup that you have. I suggest that you add some logging in your application to see what is going on. A good idea is to add logging to the middleware to see what is going on in your request lifecycle. 

Note that the user info is determined [here](https://github.com/kyranb/Footprints/blob/a9c7f7572d1f606daa06e0ac1957beb542b88b3f/src/TrackingLogger.php#L23): 

```php
        $job = new TrackVisit($this->captureAttributionData(), Auth::user() ? Auth::user()->id : null);
```

**Comment by mzaman** [comment]
Hi @bilfeldt 
Thank you for your feedback. I believe it's a new feature.
For a clearer understanding, consider a similar implementation in this pull request: https://github.com/kyranb/Footprints/pull/45/files. The associated issue is documented here: https://github.com/kyranb/Footprints/pull/45#issue-816907180. This feature mirrors the existing implementation but introduces an additional tracking event for subsequent logins, can be identified as "LoginTracked." The goal is to establish a link between the initial visit and subsequent visits during the next login by the same user. Feel free to ask if you have any questions or need further clarification.

**Comment by bilfeldt** [comment]
@mzaman do I understand you correctly that you are not reporting a bug, but requesting a feature?

There is a bunch of Auth events already fired in the system that might be relevant for you: https://github.com/laravel/framework/tree/10.x/src/Illuminate/Auth/Events

**Comment by mzaman** [comment]
@bilfeldt 
Thank you for the URL.
We can consider this case so that it might be a potential issue. Similar to case #45, if it's regarded as an issue or requirement, the current case deserves the same attention. The challenge lies in the absence of a link between the initial visit and other attribution records in database, even when performed by the same user. 

This gap becomes evident, when an existing user, already registered within the application, is redirected with UTM parameters during logout state, the initial attribution trace is lost. This instance is critical as tracking the first visit is pivotal in certain use cases, impacting accurate tracking. Addressing this is crucial for comprehensive record-keeping.

**Comment by bilfeldt** [comment]
Can you provide a repo with a clean Laravel installation where this issue is replicated?

**Comment by mzaman** [comment]
@bilfeldt 
Thank you for your patience. I'll share the repository once it's complete. 
Here's the scenario: `When an existing user, already registered in the application, is redirected with UTM parameters during the logout state, the initial attribution trace is lost.` 
I believe assigning previous visits on the next login is the key to the solution.

**Comment by bilfeldt** [comment]
> @bilfeldt Thank you for your patience. I'll share the repository once it's complete. Here's the scenario:
> 
> > when an existing user, already registered in the application, is redirected with UTM parameters during the logout state, the initial attribution trace is lost.
> 
> I believe assigning previous visits on the next login is the key to the solution.

I am not sure I get the flow. Can you try to sketch the request flow something like so;

1. (unauthenticated): GET /foo?utm......
2. ....
