### ISSUE TITLE
Multiple models

### ISSUE THREAD

**Issue by liran-co** [kyranb/Footprints#21]
It would be nice if we could track multiple models instead of just one. Using a [morphables](https://laravel.com/docs/5.8/eloquent-relationships#polymorphic-relationships), you could have model_type and model_id columns. This is useful when we have registration for several different models.

**Comment by kyranb** [comment]
Sounds good! Would happily accept a PR :)

**Comment by bilfeldt** [comment]
This is implemented in #39 and can now be achieved by making the required modifications to the migration file and then implementing whatever logic is needed in `assignPreviousVisits()` method in `TrackRegistrationAttribution`.

@kyranb If this should be more "natively" implemented then it would require switching to `morphables` as mentioned in the original message, but it would probably also require switching to a many-to-many relationship in order to handle multiple models being created which could all related to the same previous visits.

In my humble opinion, this is an edge case, and being that it is already possible to achieve this edge case behaviour by implementing custom logic classes as explained above, then I would not recommend going for a more "native" solution and hence closing this issue based on the new options made available in #39 and #36 - but again, this is **my** subjective opinion based on **my** needs.

**Comment by kyranb** [comment]
I guess most people are using this to track attribution for either 'users' or 'tenants' but I'd love to hear of other use cases where multiple models are needed to be tracked?
