### ISSUE TITLE
TrackVisit using authenticated user id

### ISSUE THREAD

**Issue by liran-co** [kyranb/Footprints#30]
The TrackUser function is using the authenticated user id even if we are using a different model:

`$user[config('footprints.column_name')] = Auth::user() ? Auth::user()->id : null;`

**Comment by kyranb** [comment]
Willing to accept a PR for this :)

**Comment by bilfeldt** [comment]
@kyranb This was solved in #36 since it is now possible to implement a custom class which implement `TrackingLoggerInterface` and implements another was of logging in the method `track(Request $request, Response $response)`. Note that the new class should be referenced in the configuration setting `tracking_logger`.

**Comment by kyranb** [comment]
👏👏  Thanks 😄
